version: '3.0'


services:
    mongo-client:
      image: mongoclient/mongoclient
      container_name: my-mongoclient
      restart: always
      ports:
        - 3003:3000
      networks: 
        - backend

networks:
    backend:
        driver: bridge